### ISSUE TITLE
Wordpress Import failed

### ISSUE THREAD

**Issue by pulkitduggar** [WeTeam/WeBlog#128]
I have installed weblog and am trying to import wordpress export xml following the same steps written here.
The import start but fails with the exception. Checked in the log file and below is the stacktrace 

ManagedPoolThread #10 18:21:34 INFO  Job started: Creating and importing blog
ManagedPoolThread #10 18:21:34 ERROR Exception
Exception: System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
Source: mscorlib
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj)
   at Sitecore.Jobs.JobRunner.RunMethod(JobArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Jobs.Job.ThreadEntry(Object state)

Nested Exception

Exception: System.Xml.XmlException
Message: '', hexadecimal value 0x18, is an invalid character. Line 80571, position 981.
Source: System.Xml
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseCDataOrComment(XmlNodeType type, Int32& outStartPos, Int32& outEndPos)
   at System.Xml.XmlTextReaderImpl.ParseCDataOrComment(XmlNodeType type)
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at Sitecore.Modules.WeBlog.Import.WpImportManager.Import(String fileLocation, Boolean includeComments, Boolean includeCategories, Boolean includeTags)
   at Sitecore.Modules.WeBlog.sitecore.shell.Applications.WeBlog.WordpressImport.ImportBlog()

**Comment by alan-null** [comment]
hi @pulkitduggar,

I am afraid that it will be really hard for us to reproduce your case without similar input data.
From the error log I can see that problem occurred in system class (not int WeBlog itself) while trying to load xml content into xml document.

Possible options:
1. Please open your exported XML file and go to the specific line and try to confirm if  exported data isn't corrupted.
2. provide us a part of your file with wrong content and we will try to determine what is the problem.
(you can send it to me via email alan-null@outlook.com or clean XML, removing data that you cannot share and attaching it here).

**Comment by alan-null** [comment]
Closed due to lack of activity.
