### ISSUE TITLE
Value cannot be null. Parameter name: Key

### ISSUE THREAD

**Issue by alpasarupria** [WeTeam/WeBlog#175]
I am facing issue in Sitecore presentation details. While clicking on Presentation -->Details, popup appears but edit functionality is not working. Clicking on Edit button does not fire any event. And sometimes it gives above error. Please help!!

**Comment by adeneys** [comment]
I am unable to reproduce.

Could you please provide the following information:

- Which Sitecore version are you using?
- Which item template are you trying to set presentation details for? (blog, category, entry)
- Which UI are you using to set the presentation details (content editor, experience editor)
- Are you trying to edit OOTB presentation or has it already been changed previously?

**Comment by alpasarupria** [comment]
I am using sitecore version 8. I am getting this error while i am restoring my production data to my local machine. On production it is running fine. But when taking the same copy of production to local it is giving error in presentation detail.

**Comment by adeneys** [comment]
Could you provide the other information I requested? Also, are there any errors in the log file?

**Comment by alpasarupria** [comment]
When i am trying to add presentation detail on any page. 
![capture](https://cloud.githubusercontent.com/assets/2264224/16442009/937f6b7e-3dec-11e6-9880-a6ad85d5a1d7.PNG)

Then i am getting this error :

`Exception: System.ArgumentNullException
Message: Value cannot be null.
Parameter name: key
Source: mscorlib
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.SelectionMappingRenderTraceListener.GetLiteralTraceData(LiteralControl literal, TraceData& data)
   at Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.SelectionMappingRenderTraceListener.GetTraceData(Object renderedObject)
   at Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.SelectionMappingRenderTraceListener.EndRendering(TextWriter writer, Object renderedObject)
   at System.Web.UI.RenderTraceListener.RenderTraceListenerList.EndRendering(TextWriter writer, Object renderedObject)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at Sitecore.Web.UI.XmlControls.GenericControl.DoRender(HtmlTextWriter output)
   at Sitecore.Web.UI.WebControl.Render(HtmlTextWriter output)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.OptimizeControlTree(Control control)
   at Sitecore.Web.UI.Sheer.ClientPage.SaveViewState()
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Page.SaveAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
`

**Comment by adeneys** [comment]
From the error above, it's difficult to determine what the issue might be and whether it's WeBlog related or not.

- Are you able to set presentation on other items (non-WeBlog items)?
- Are you able to create a new blog (from the blog branch) and set presentation on any of the items in the new blog?
- Are you able to create a new item based on the `Sample item` template and set presentation for it?

**Comment by alan-null** [comment]
Closed due to lack of activity.
