### ISSUE TITLE
submitting a comment on CD server

### ISSUE THREAD

**Issue by jelaydi** [WeTeam/WeBlog#231]
Hello,

I have upgraded weblog module to 3.0 for sitecore 8.2 initial release. I have a content authoring and content delivery environments. If I submit a comment from the CM server, it works just fine and adds the comment to the entry. However if I submit the comment from the CD server, it gives me the following error and doesn't submit the comment:

Server Error in '/' Application.

Object reference not set to an instance of an object.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ServiceModel.FaultException`1[[System.ServiceModel.ExceptionDetail, System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]: Object reference not set to an instance of an object.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[FaultException`1: Object reference not set to an instance of an object.]
   System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) +14581778
   System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) +622
   Sitecore.Modules.WeBlog.Services.ICommentService.SubmitComment(ID EntryId, Comment comment, Language language) +0
   Sitecore.Modules.WeBlog.Managers.CommentManager.SubmitComment(ID entryId, Comment comment, Language language) +158
   Sitecore.Modules.WeBlog.WebForms.Layouts.BlogSubmitComment.buttonSaveComment_Click(Object sender, EventArgs e) +401
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +155
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3804

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.36366

Any idea what I might be missing.

I did the following steps for the multi server setup:

https://github.com/WeTeam/WeBlog/wiki/Multi-Server-Setup

Kindly assist.

Thank you,

**Comment by adeneys** [comment]
Hi Jelaydi,
Are there any additional details provided in the Sitecore log file? The above message just indicates there was an issue with the WCF components, so the likely cause is misconfiguration for your environment.

Can you also describe the topology of your network? Are the CM and CD servers on the same network or different networks?

**Comment by jelaydi** [comment]
Hello,

well this is what i found in the log file ::
8296 06:43:00 ERROR Application error.
Exception: System.Web.HttpUnhandledException
Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Source: System.Web
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.layouts_weblog_layout_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\68f4bed9\f9cda536\App_Web_xu1rkz2y.15.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Nested Exception

Exception: System.ServiceModel.FaultException`1[[System.ServiceModel.ExceptionDetail, System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
Message: Object reference not set to an instance of an object.
Source: mscorlib

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Sitecore.Modules.WeBlog.Services.ICommentService.SubmitComment(ID EntryId, Comment comment, Language language)
   at Sitecore.Modules.WeBlog.Managers.CommentManager.SubmitComment(ID entryId, Comment comment, Language language)
   at Sitecore.Modules.WeBlog.WebForms.Layouts.BlogSubmitComment.buttonSaveComment_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
[log.20170115.051648.txt](https://github.com/WeTeam/WeBlog/files/708268/log.20170115.051648.txt)
CM and CD are on the same network yes.. and it used to work on older versions.. not sure if I missed anything this time..

**Comment by adeneys** [comment]
Not sure if this issue is still active, but we just fixed an issue related to the profanity filter when invoked through the WCF service. The fix is available in release 4.0.1.

**Comment by adeneys** [comment]
Closing this issue due to inactivity. Please reopen it if the issue is still present in the last release.
