### ISSUE TITLE
Duplicate key error when a blog entry item has more than 1 version

### ISSUE THREAD

**Issue by IvanSheyenko** [WeTeam/WeBlog#249]
1.	Create a blog
2.	Create a blog entry with at least 2 item versions
3.	Publish everything
4.	Visit created entry on a site
5.	Wait for session to expire
6.	Preview blog item from step 1

The following error is shown:
```
Exception: System.ArgumentException
Message: An item with the same key has already been added.
Source: mscorlib
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Sitecore.Modules.WeBlog.Managers.EntryManager.GetPopularEntriesByView(Item blogItem, Int32 maxCount)
   at Sitecore.Modules.WeBlog.WebForms.Layouts.Sidebar.BlogInterestingEntries.Page_Load(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at Sitecore.Modules.WeBlog.WebForms.Layouts.BaseSublayout.OnLoad(EventArgs e)
```

**Comment by alan-null** [comment]
Issue solved here: #250

Thank you once again @IvanSheyenko for your contribution.
