### ISSUE TITLE
WordPress import issue

### ISSUE THREAD

**Issue by cv1998** [WeTeam/WeBlog#253]
Hi,
i'm using Sitecore 8.1 rev. 160519 and WeBlog-3.1.0_sc8.0-8.1.
when trying to import the xml file from WordPress, i got this error

Job started: Creating and importing blog
Reading import file
Creating blog
Importing posts
#Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.FormatException: String was not recognized as a valid DateTime because the day of week was incorrect.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at Sitecore.Modules.WeBlog.Import.WpPost.GetPost(XElement postXml, Boolean includeComments, Boolean includeCategories, Boolean includeTags)
   at Sitecore.Modules.WeBlog.Import.Providers.FileBasedProvider.<>c__DisplayClass2_0.<GetPosts>b__0(XElement item)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Sitecore.Modules.WeBlog.Import.Providers.FileBasedProvider.GetPosts(WpImportOptions options)
   at Sitecore.Modules.WeBlog.sitecore.shell.Applications.WeBlog.WordpressImport.ImportBlog()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Jobs.Job.ThreadEntry(Object state)

Here is pubDate in the xml file

<pubDate>Tue, 15 Aug 2017 14:34:30 +0000</pubDate>

I'm not sure what is wrong with this format.

Thanks

**Comment by cv1998** [comment]
Update.
I found an incorrect date format in the xml and removed it. I did not get that error any more.

Thanks

**Comment by andyram2k** [comment]
Hi @cv1998 , i'm having the same issue - which date format was wrong please? I'm struggling to work out why the import fails, and there's lots of entries in the XML i'm trying to import.

Many thanks,

Andy

**Comment by alan-null** [comment]
Hi @andyram2k,

Unfortunately, it is impossible right now to see which part of XML has an incorrect date.
I will add a task to our backlog to address this issue.

For now, I can suggest following solutions:
- split your XML into half, try to import, see if error occur in first half, if not then incorrect date is in second, repeat until you get incorrect date (time consuming)
- if you are not afraid, you can use this `exe`, 
[WeBlogImportValidatorEXE.zip](https://github.com/WeTeam/WeBlog/files/1460652/WeBlogImportValidatorEXE.zip) (usage, unpack into some folder, put xml file into it, double click exe)
![image](https://user-images.githubusercontent.com/6848691/32650019-8255caf2-c5fc-11e7-94d2-61d81351862b.png)
- if you want to review code before and build it by yourself, here you go
[WeBlogImportValidator.zip](https://github.com/WeTeam/WeBlog/files/1460650/WeBlogImportValidator.zip)
