### ISSUE TITLE
Use component specific logger

### ISSUE THREAD

**Issue by adeneys** [WeTeam/WeBlog#97]
It's much easier to find entries specific to a component if the component tags it's log entries. Rather than trying to remember to add a tag to each entry it's easier to create a component specific logger class and use that instead.

Instead of:
    Log.Error("[WeBlog] this is a message", this);

Create the `Logger` class and use that:
    Logger.Error("This is a message")

**Comment by alan-null** [comment]
### Example code
```csharp
protected void Page_Load(object sender, EventArgs e)
{
    try
    {
        Item x = new Item(new ID("1234"), null, null);
    }
    catch (Exception exception)
    {
        Logger.Warn("Logger.Warn");
        Logger.Error("Error occured", exception, this);
    }
    LoadTags();
}
```

### Example log
```
11720 22:15:00 INFO  Cache created: 'Feed Manager - Feeds' (max size: 100KB, running total: 2188MB)
11720 22:15:00 WARN  [WeBlog][BlogTagCloud] Logger.Warn
11720 22:15:00 ERROR [WeBlog][BlogTagCloud] Error occured
Exception: System.FormatException
Message: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
Source: mscorlib
   at System.Guid.TryParseGuidWithNoStyle(String guidString, GuidResult& result)
   at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result)
   at System.Guid..ctor(String g)
   at Sitecore.Data.ID..ctor(String id)
   at Sitecore.Modules.WeBlog.Layouts.BlogTagCloud.Page_Load(Object sender, EventArgs e) in C:\REPOSITORIES\Open Source\WeBlog\Website\layouts\WeBlog\Sidebar\TagCloud.ascx.cs:line 24

16632 22:15:01 INFO  HttpModule is being initialized
14288 22:15:01 INFO  HttpModule is being initialized
```
